### ISSUE TITLE
Pull Request 템플릿을 만들어야 해요.

### ISSUE THREAD

**Issue by bbearcookie** [prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun#2]
## 작업 해야 할 일이 어떤 분류에 속하나요? O 표시로 괄호를 채워주세요!
- 기능 추가 ( )
- 기능 수정 ( )
- 버그 수정 ( )
- 리팩토링 ( )
- 스타일 작업 ( )
- 패키지 작업 ( )
- 문서 작업 (O)
- 기타 작업 ( )

## 구체적으로 어떤 작업을 진행해야 하나요?
PR 템플릿을 만들어야 해요.

**Comment by juyeon-park** [comment]
PR 템플릿 구현 완료했습니다!
